# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

variables:
  DOXYGEN_URL: "https://www.doxygen.nl/files/doxygen-1.9.2.windows.x64.bin.zip"
  DOXYGEN_WORKINGDIR: '$(Pipeline.Workspace)\Documentation\Doxygen'
  DOXYGEN_OUTPUT: '$(Pipeline.Workspace)\Documentation\Output'
steps:
- checkout: self
  clean: true
  persistCredentials: true

- task: Cache@2
  displayName: "Cache Doxygen Install"
  inputs:
    key: '"$(doxygenUrl)"'
    path: $(DOXYGEN_WORKINGDIR)
    cacheHitVar: 'CACHE_RESTORED'

- task: PowerShell@2
  displayName: "Download Doxygen"
  condition: ne(variables.CACHE_RESTORED, 'true')
  inputs:
    targetType: 'inline'
    script: |
      $doxygenUrl = ${env:DOXYGEN_URL}
      $outpath = ${env:DOXYGEN_WORKINGDIR}
      
      if(!(Test-Path $outpath))
      {
      	Write-Host "Creating $outpath";
      	New-Item -ItemType Directory -Force -Path $outpath
      }
      $zipDownloadPath = "$outpath\" + $(Split-Path -Path $doxygenUrl -Leaf)
      Write-Host "Downloading from $doxygenUrl to $zipDownloadPath"
      
      Invoke-WebRequest -Uri $doxygenUrl -OutFile $zipDownloadPath
      Expand-Archive -LiteralPath $zipDownloadPath -DestinationPath $outpath
      Remove-Item $zipDownloadPath

- task: PowerShell@2
  displayName: "Run Doxygen"
  inputs:
    targetType: 'inline'
    script: |
      $(DOXYGEN_WORKINGDIR)\doxygen.exe $(Build.SourcesDirectory)\Documentation\DoxygenConfigAzurePipelines

- task: PowerShell@2
  displayName: "Commit Documentation to GitHub Pages"
  inputs:
    targetType: 'inline'
    script: |
      git config user.email "hen.bagle@gmail.com"
      git config user.name "ME3Tweaks-LEC-Documentation"
      git checkout gh-pages
      Remove-Item .\nightly\* -Recurse
      Copy-Item -Path "$(DOXYGEN_OUTPUT)\html\*" -Destination .\nightly -Recurse
      git add .\nightly\
      git commit -m "Update documentation [skip ci]"
      git push origin gh-pages