# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

variables:
  DOXYGEN_WORKINGDIR: '$(Pipeline.Workspace)\doxygen'
  DOXYGEN_OUTPUT: '$(Pipeline.Workspace)'
steps:
# - task: Cache@2
#   displayName: "Cache Doxygen Install"
#   inputs:
#     key: '"$(doxygenUrl)"'
#     path: $(DOXYGEN_WORKINGDIR)
#     cacheHitVar: 'CACHE_RESTORED'
    
- task: PowerShell@2
  displayName: "Download Doxygen"
  inputs:
    targetType: 'inline'
    script: |
      $doxygenUrl = ${env:DOXYGENURL}
      $outpath = ${env:DOXYGEN_WORKINGDIR}
      
      if($null -eq $doxygenUrl)
      {
          $doxygenUrl = "https://www.doxygen.nl/files/doxygen-1.9.2.windows.x64.bin.zip"
      }
      
      if(!(Test-Path $outpath))
      {
      	Write-Host "Creating $outpath";
      	New-Item -ItemType Directory -Force -Path $outpath
      }
      $zipDownloadPath = "$outpath\" + $(Split-Path -Path $doxygenUrl -Leaf)
      Write-Host "Downloading from $doxygenUrl to $zipDownloadPath"
      
      Invoke-WebRequest -Uri $doxygenUrl -OutFile $zipDownloadPath
      Expand-Archive -LiteralPath $zipDownloadPath -DestinationPath $outpath
      Remove-Item $zipDownloadPath
- task: PowerShell@2
  displayName: "Run Doxygen"
  inputs:
    targetType: 'inline'
    script: |
      $(DOXYGEN_WORKINGDIR)\doxygen.exe $(Build.SourcesDirectory)\DoxygenConfigLEC